import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display, Montserrat, Zalando_Sans_Expanded } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  display: "swap", // Ensure smooth swapping
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  display: "swap", // Ensure smooth swapping
});

const zalandoSans = Zalando_Sans_Expanded({
  variable: "--font-zalando-sans",
  subsets: ["latin"],
  display: "swap", // Ensure smooth swapping
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Toaster } from "@/components/ui/sonner";
import { LayoutLoaderProvider } from "@/components/layout/layout-loader-provider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} ${montserrat.variable} ${zalandoSans.variable} font-sans antialiased`}>
      <body>
        <LayoutLoaderProvider>
          {children}
          <Toaster position="top-center" richColors />
        </LayoutLoaderProvider>
      </body>
    </html>
  );
}
