import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display, Montserrat, Special_Gothic_Expanded_One } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap", // Ensure smooth swapping
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  display: "swap",
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  display: "swap",
});

const SpecialGothicExpandedOne = Special_Gothic_Expanded_One({
  variable: "--font-expanded-sans",
  weight: "400",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Bit & Bloom Showcase",
  description: "Generated by create next app",
};

import { Toaster } from "@/components/ui/sonner";
import { LayoutLoaderProvider } from "@/components/layout/layout-loader-provider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} ${montserrat.variable} ${SpecialGothicExpandedOne.variable} font-sans antialiased`}>
      <body>
        <LayoutLoaderProvider>
          {children}
          <Toaster position="top-center" richColors />
        </LayoutLoaderProvider>
      </body>
    </html>
  );
}
